# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR) <https://dlr.de>
#
# SPDX-License-Identifier: MIT
# Here are some commonly used pre-commit hooks. You can find more at:
# <https://github.com/pre-commit/pre-commit-hooks>
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/fsfe/reuse-tool
  rev: v5.0.2
  hooks:
  - id: reuse
    name: Check license headers (REUSE)
- repo: https://github.com/citation-file-format/cffconvert
  rev: b6045d78aac9e02b039703b030588d54d53262ac
  hooks:
  - id: validate-cff
    name: Validate CITATION.cff file
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    name: Fixing common spelling mistakes
    args:
    - --write-changes
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.0
  hooks:
  - id: check-github-workflows
    name: Check GitHub Workflow configuration
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.0.3
  hooks:
  - id: editorconfig-checker
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.43.0
  hooks:
  - id: markdownlint
    name: Fixing markdown linting errors
    args: [--disable, MD013, MD033, --fix]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', CITATION.cff]
  - id: pretty-format-toml
    args: [--autofix]
