# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR) <https://dlr.de>
#
# SPDX-License-Identifier: MIT
name: Running pre-commit (pre-commit)

on:
  push:
    branches:
    - main
    - develop
    - releases/**
  pull_request:
    branches:
    - main
    - develop

permissions:
  contents: read

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Running pre-commit
      uses: pre-commit/action@v3.0.1
